### ISSUE TITLE
Scraper not recognizing certain links

### ISSUE THREAD

**Issue by ThrillBird** [jordond/romtool#1]
#First of all, thanks a lot for this great tool! I haven't played around too much, but I noticed a minor issue with the scraper. It wasn't able to find any links in two of the archives I tried. Specifically :

Httpsarchive.orgdetailsRedumpNintendoWiiAmericaPart6 (yes that is the actual identifier, guess the uploader messed up somewhere) 

RedumpNintendoWiiAmericaPart3_201802

My instant thought was that your scraper got confused by the punctuation and underscore, but I'm not sure. It's certainly not a big problem especially since both those archives are still live, but I thought I'd should at least let you know about it in case you feel like looking into it!

Thanks again! 

Edit: Okay, seems like I've misunderstood the whole thing a little - it is only supposed to grab any dead links. Still, a feature to grab all links would be great!

**Comment by jordond** [comment]
Sorry for the late reply.  I will certainly look into adding an option for grabbing all links not just the dead ones.

**Comment by jordond** [comment]
Easier than I thought.

New version is on [npm](https://www.npmjs.com/package/romtool)
