### ISSUE TITLE
Can't create playlists for games with suffix after (Disc x)

### ISSUE THREAD

**Issue by tcamargo** [jordond/romtool#3]
Hi,

I can't create playlist for some of my PSX games. All of them have some text after (Disc X).

````
ℹ /roms/psx/Final Fantasy IX (USA) =>
        Final Fantasy IX (USA) (Disc 1) (v1.1).bin
        Final Fantasy IX (USA) (Disc 1) (v1.1).cue
        Final Fantasy IX (USA) (Disc 2) (v1.1).bin
        Final Fantasy IX (USA) (Disc 2) (v1.1).cue
        Final Fantasy IX (USA) (Disc 3) (v1.1).bin
        Final Fantasy IX (USA) (Disc 3) (v1.1).cue
        Final Fantasy IX (USA) (Disc 4) (v1.1).bin
        Final Fantasy IX (USA) (Disc 4) (v1.1).cue
ℹ found cues -> 0, found bins -> 0
ℹ no cues or bins were found in /roms/psx/Final Fantasy IX (USA)
ℹ /roms/psx/Metal Gear Solid (USA) =>
        Metal Gear Solid (USA) (Disc 1) (v1.1).bin
        Metal Gear Solid (USA) (Disc 1) (v1.1).cue
        Metal Gear Solid (USA) (Disc 2) (v1.1).bin
        Metal Gear Solid (USA) (Disc 2) (v1.1).cue
ℹ found cues -> 0, found bins -> 0
ℹ no cues or bins were found in /roms/psx/Metal Gear Solid (USA)
````

I think is related to this line:
https://github.com/jordond/romtool/blob/18a467a5d554fb5b515e26f341c5968f89bd26ad/src/commands/playlist/playlist.handler.js#L213

I am not a JS programmer, so excuse me if I got it wrong. :)

Thanks!

**Comment by jordond** [comment]
Weird, could've sworn my own collection contains files like that.  I'll take a look when I get home.

**Comment by tcamargo** [comment]
Hi. I was wondering if you had the chance to check this. Thanks!

**Comment by jordond** [comment]
Yes sorry, I found the problem.  For some reason I wasn't using the proper regex variable (the one above doesn't include the `*`).  I will push a fix shortly.

**Comment by jordond** [comment]
Fixed in release 1.1.0.

**Comment by tcamargo** [comment]
1.1.0 or 1.2.0? :)

**Comment by jordond** [comment]
Sorry 1.2.0 🙃

**Comment by tcamargo** [comment]
Thanks! It's perfect now!
